### PR TITLE
global: PyTest docstring improvement

### PR DESCRIPTION
**Pull request by JavierDelgadoFernandez**
* BETTER initialize_options docstring

* BETTER finalize_options docstring

* BETTER run_test docstring

Signed-off-by: Javier Fernandez <javier.delgado.fernandez@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@JavierDelgadoFernandez please use `BETTER` labels only for messages that should be mentioned in `RELEASE-NOTES.rst`.

**Comment by JavierDelgadoFernandez** [comment]
@jirikuncar The commit is updated with the correct message.

**Comment by tiborsimko** [comment]
Note that you can simplify the commit message even further, i.e. the individual subpoints are not really necessary here...

**Comment by JavierDelgadoFernandez** [comment]
@tiborsimko @jirikuncar I have recommitted my changes improving the commit message.

**Pull request merged**
